(source "melpa")

(package "company-emojify" "0.1.0" "Company completion for Emojify")

(package-file "company-emojify.el")

(depends-on "emacs" "26.1")
(depends-on "company")
(depends-on "emojify")
(depends-on "ht")

(development
 (depends-on "ert-runner"))

(setq network-security-level 'low      ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
      byte-compile-error-on-warn nil)
